<?= $this->include('layouts/header') ?>
<section class="hero p-5 mb-4">
    <div class="row align-items-center g-4 position-relative" style="z-index:1">
        <div class="col-lg-7">
            <div class="text-uppercase fw-bold small mb-3" style="letter-spacing:.12em"><i class="fa-solid fa-heart-pulse me-2"></i>Care that comes to you</div>
            <h1 class="display-5 fw-bold lh-sm mb-3">Your everyday health,<span class="d-block">made reassuringly simple.</span></h1>
            <p class="lead mb-4 opacity-75">Genuine medicines, transparent prices, and pharmacist-guided care delivered to your doorstep.</p>
            <div class="d-flex gap-2 flex-wrap"><a class="btn btn-light text-success" href="<?= site_url('shop') ?>">Explore medicines <i class="fa-solid fa-arrow-right ms-1"></i></a><a class="btn btn-outline-light" href="<?= site_url('shop?prescription_required=1') ?>"><i class="fa-solid fa-file-prescription me-1"></i>Prescription care</a></div>
            <div class="d-flex flex-wrap gap-4 mt-4 small fw-semibold"><span><i class="fa-solid fa-circle-check me-1"></i>100% genuine</span><span><i class="fa-solid fa-truck me-1"></i>Fast delivery</span><span><i class="fa-solid fa-user-doctor me-1"></i>Pharmacist support</span></div>
        </div>
        <div class="col-lg-5"><div class="bg-white text-dark rounded-4 p-4 shadow-lg"><span class="section-kicker">Find what you need</span><h5 class="fw-bold mt-1 mb-3">Search medicines & wellness</h5><form action="<?= site_url('shop') ?>" method="get"><div class="input-group mb-3"><span class="input-group-text bg-white border-end-0"><i class="fa-solid fa-magnifying-glass text-success"></i></span><input type="text" name="q" class="form-control border-start-0" placeholder="e.g. Paracetamol, vitamins"></div><button class="btn btn-success w-100">Search medicines</button></form><p class="small text-muted mb-0 mt-3"><i class="fa-solid fa-lock me-1"></i>Your health information stays private.</p></div></div>
    </div>
</section>
<section class="feature-strip row g-0 mb-5"><div class="col-md-4 feature d-flex align-items-center gap-3"><i class="fa-solid fa-capsules"></i><div><strong>Quality you can trust</strong><div class="small text-muted">Authentic pharmacy products</div></div></div><div class="col-md-4 feature d-flex align-items-center gap-3"><i class="fa-solid fa-truck-fast"></i><div><strong>On-time delivery</strong><div class="small text-muted">Carefully packed and delivered</div></div></div><div class="col-md-4 feature d-flex align-items-center gap-3"><i class="fa-solid fa-headset"></i><div><strong>Here when needed</strong><div class="small text-muted">Helpful pharmacy support</div></div></div></section>
<section class="mb-5"><div class="d-flex justify-content-between align-items-end mb-3"><div><span class="section-kicker">Shop by need</span><h2 class="section-title h3 mb-0">Popular categories</h2></div><a class="text-success fw-semibold text-decoration-none small" href="<?= site_url('shop') ?>">View all <i class="fa-solid fa-arrow-right ms-1"></i></a></div><div class="d-flex flex-wrap gap-2"><?php foreach ($categories as $category): ?><a class="btn btn-outline-success" href="<?= site_url('shop?category_id=' . (int) $category['id']) ?>"><i class="fa-solid fa-circle-plus me-1"></i><?= esc($category['name']) ?></a><?php endforeach; ?></div></section>
<?php if (!empty($banners) || !empty($offers)): ?><section class="row g-4 mb-5"><?php foreach (array_slice(array_merge($banners ?? [], $offers ?? []), 0, 2) as $index => $promotion): ?><div class="col-md-6"><div class="card card-hover h-100 overflow-hidden"><div class="card-body p-4 <?= $index === 0 ? 'bg-success-subtle' : 'bg-info-subtle' ?>"><span class="section-kicker">Limited-time offer</span><h3 class="h5 fw-bold mt-2"><?= esc($promotion['title']) ?></h3><p class="text-muted mb-3"><?= esc($promotion['subtitle'] ?? $promotion['description'] ?? 'Healthy savings for your everyday essentials.') ?></p><?php if (!empty($promotion['discount_percent'])): ?><span class="badge bg-success me-2"><?= (float) $promotion['discount_percent'] ?>% OFF</span><?php endif; ?><a class="text-success fw-bold text-decoration-none small" href="<?= esc($promotion['link'] ?? site_url('offers')) ?>">Shop offer <i class="fa-solid fa-arrow-right ms-1"></i></a></div></div></div><?php endforeach; ?></section><?php endif; ?>
<section class="mb-5"><div class="d-flex justify-content-between align-items-end mb-3"><div><span class="section-kicker">Handpicked for you</span><h2 class="section-title h3 mb-0">Featured medicines</h2></div><a class="text-success fw-semibold text-decoration-none small" href="<?= site_url('shop') ?>">Browse all <i class="fa-solid fa-arrow-right ms-1"></i></a></div><div class="row g-4"><?php foreach ($featuredMedicines as $medicine): ?><div class="col-sm-6 col-lg-3"><div class="card medicine-card h-100 card-hover"><a href="<?= site_url('medicine/' . rawurlencode($medicine['slug'])) ?>"><img src="<?= esc(upload_url($medicine['image'])) ?>" onerror="this.onerror=null;this.src='<?= base_url('assets/img/placeholder-medicine.png') ?>';" class="card-img-top medicine-image" alt="<?= esc($medicine['name']) ?>"></a><div class="card-body d-flex flex-column"><div class="medicine-meta mb-1"><?= esc($medicine['category_name'] ?? 'Healthcare') ?></div><a class="medicine-card-title fw-bold mb-1" href="<?= site_url('medicine/' . rawurlencode($medicine['slug'])) ?>"><?= esc($medicine['name']) ?></a><p class="medicine-meta mb-3"><?= esc($medicine['manufacturer_name'] ?? $medicine['generic_name'] ?? 'Trusted pharmacy product') ?></p><div class="mt-auto"><div class="d-flex align-items-center gap-2 mb-3"><span class="price-current"><?= format_price(medicine_price($medicine)) ?></span><?php if (!empty($medicine['discount_price']) && (float) $medicine['discount_price'] < (float) $medicine['price']): ?><span class="price-old"><?= format_price($medicine['price']) ?></span><?php endif; ?></div><div class="medicine-actions"><a class="btn btn-outline-success" href="<?= site_url('medicine/' . rawurlencode($medicine['slug'])) ?>">Details</a><form method="post" action="<?= site_url('cart/add/' . (int) $medicine['id']) ?>" class="flex-fill"><?= csrf_field() ?><input type="hidden" name="quantity" value="1"><button class="btn btn-success w-100" type="submit"><i class="fa-solid fa-bag-shopping me-1"></i>Add</button></form></div></div></div></div></div><?php endforeach; ?></div></section>
<section class="row g-4 align-items-stretch mb-5"><div class="col-lg-7"><div class="card h-100"><div class="card-body p-4 p-lg-5"><span class="section-kicker">Expert guidance</span><h2 class="section-title h3 mt-2">A little more confidence with every order.</h2><p class="text-muted">From prescription support to product questions, our pharmacy team helps you make informed choices for everyday care.</p><a class="btn btn-outline-success" href="<?= site_url('contact') ?>">Talk to our care team</a></div></div></div><div class="col-lg-5"><div class="card h-100 bg-success text-white border-0"><div class="card-body p-4 p-lg-5"><i class="fa-solid fa-quote-left fs-2 opacity-50 mb-3"></i><p class="fs-5 fw-semibold">“Ordering our family’s essentials has never felt this easy and dependable.”</p><div class="small opacity-75">— A MediStore customer</div></div></div></div></section>
<?= $this->include('layouts/footer') ?>
